### ISSUE TITLE
请问，你这个库能直接使用ZK4500指纹扫描么？还是需要经过一个windows程序转换？

### ISSUE THREAD

**Issue by zouhuigang** [am05mhz/am05zk#1]

**Comment by am05mhz** [comment]
Hi, sorry for the late reply, as I was quiet busy lately. This library is used to directly collect attendance data from the device, but unfortunately, only 2 SDK version that is partially supported. This is mainly because there are lots of little variation between versions and lack of documentation for it. And sorry I don't understand Mandarin or Chinese, I can reply you because of translation tools.

**Comment by zouhuigang** [comment]
Okay, thank you。 I've solved it, you use Chinese equipment, and I thought you were Chinese, sorry.
